package com.aso.itsdf07.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DemoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_id
     *
     * @mbggenerated
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_username
     *
     * @mbggenerated
     */
    private String dUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_password
     *
     * @mbggenerated
     */
    private String dPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_displayname
     *
     * @mbggenerated
     */
    private String dDisplayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_age
     *
     * @mbggenerated
     */
    private Integer dAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_balance
     *
     * @mbggenerated
     */
    private BigDecimal dBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_demo.d_create_time
     *
     * @mbggenerated
     */
    private Date dCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_id
     *
     * @return the value of t_demo.d_id
     *
     * @mbggenerated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_id
     *
     * @param dId the value for t_demo.d_id
     *
     * @mbggenerated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_username
     *
     * @return the value of t_demo.d_username
     *
     * @mbggenerated
     */
    public String getdUsername() {
        return dUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_username
     *
     * @param dUsername the value for t_demo.d_username
     *
     * @mbggenerated
     */
    public void setdUsername(String dUsername) {
        this.dUsername = dUsername == null ? null : dUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_password
     *
     * @return the value of t_demo.d_password
     *
     * @mbggenerated
     */
    public String getdPassword() {
        return dPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_password
     *
     * @param dPassword the value for t_demo.d_password
     *
     * @mbggenerated
     */
    public void setdPassword(String dPassword) {
        this.dPassword = dPassword == null ? null : dPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_displayname
     *
     * @return the value of t_demo.d_displayname
     *
     * @mbggenerated
     */
    public String getdDisplayname() {
        return dDisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_displayname
     *
     * @param dDisplayname the value for t_demo.d_displayname
     *
     * @mbggenerated
     */
    public void setdDisplayname(String dDisplayname) {
        this.dDisplayname = dDisplayname == null ? null : dDisplayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_age
     *
     * @return the value of t_demo.d_age
     *
     * @mbggenerated
     */
    public Integer getdAge() {
        return dAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_age
     *
     * @param dAge the value for t_demo.d_age
     *
     * @mbggenerated
     */
    public void setdAge(Integer dAge) {
        this.dAge = dAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_balance
     *
     * @return the value of t_demo.d_balance
     *
     * @mbggenerated
     */
    public BigDecimal getdBalance() {
        return dBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_balance
     *
     * @param dBalance the value for t_demo.d_balance
     *
     * @mbggenerated
     */
    public void setdBalance(BigDecimal dBalance) {
        this.dBalance = dBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_demo.d_create_time
     *
     * @return the value of t_demo.d_create_time
     *
     * @mbggenerated
     */
    public Date getdCreateTime() {
        return dCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_demo.d_create_time
     *
     * @param dCreateTime the value for t_demo.d_create_time
     *
     * @mbggenerated
     */
    public void setdCreateTime(Date dCreateTime) {
        this.dCreateTime = dCreateTime;
    }
}