package com.aso.itsdf07.entity;

import java.util.Date;

public class GoodEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.product_name
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.seller_sku
     *
     * @mbggenerated
     */
    private String sellerSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.sku_id
     *
     * @mbggenerated
     */
    private String skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.sku_visitors
     *
     * @mbggenerated
     */
    private Integer skuVisitors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.sku_pageviews
     *
     * @mbggenerated
     */
    private Integer skuPageviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.visitor_value
     *
     * @mbggenerated
     */
    private Double visitorValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.buyers
     *
     * @mbggenerated
     */
    private Integer buyers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.orders
     *
     * @mbggenerated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.units_sold
     *
     * @mbggenerated
     */
    private Integer unitsSold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.revenue
     *
     * @mbggenerated
     */
    private Double revenue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.conversion_rate
     *
     * @mbggenerated
     */
    private Double conversionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.revenue_per_buyer
     *
     * @mbggenerated
     */
    private Double revenuePerBuyer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.wishlist_visitor
     *
     * @mbggenerated
     */
    private Integer wishlistVisitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.wishlists
     *
     * @mbggenerated
     */
    private Integer wishlists;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.add_to_car_visitors
     *
     * @mbggenerated
     */
    private Integer addToCarVisitors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.add_to_car_units
     *
     * @mbggenerated
     */
    private Integer addToCarUnits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.store
     *
     * @mbggenerated
     */
    private String store;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.datetime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.id
     *
     * @return the value of good.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.id
     *
     * @param id the value for good.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.product_name
     *
     * @return the value of good.product_name
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.product_name
     *
     * @param productName the value for good.product_name
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.seller_sku
     *
     * @return the value of good.seller_sku
     *
     * @mbggenerated
     */
    public String getSellerSku() {
        return sellerSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.seller_sku
     *
     * @param sellerSku the value for good.seller_sku
     *
     * @mbggenerated
     */
    public void setSellerSku(String sellerSku) {
        this.sellerSku = sellerSku == null ? null : sellerSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.sku_id
     *
     * @return the value of good.sku_id
     *
     * @mbggenerated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.sku_id
     *
     * @param skuId the value for good.sku_id
     *
     * @mbggenerated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.url
     *
     * @return the value of good.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.url
     *
     * @param url the value for good.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.sku_visitors
     *
     * @return the value of good.sku_visitors
     *
     * @mbggenerated
     */
    public Integer getSkuVisitors() {
        return skuVisitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.sku_visitors
     *
     * @param skuVisitors the value for good.sku_visitors
     *
     * @mbggenerated
     */
    public void setSkuVisitors(Integer skuVisitors) {
        this.skuVisitors = skuVisitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.sku_pageviews
     *
     * @return the value of good.sku_pageviews
     *
     * @mbggenerated
     */
    public Integer getSkuPageviews() {
        return skuPageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.sku_pageviews
     *
     * @param skuPageviews the value for good.sku_pageviews
     *
     * @mbggenerated
     */
    public void setSkuPageviews(Integer skuPageviews) {
        this.skuPageviews = skuPageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.visitor_value
     *
     * @return the value of good.visitor_value
     *
     * @mbggenerated
     */
    public Double getVisitorValue() {
        return visitorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.visitor_value
     *
     * @param visitorValue the value for good.visitor_value
     *
     * @mbggenerated
     */
    public void setVisitorValue(Double visitorValue) {
        this.visitorValue = visitorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.buyers
     *
     * @return the value of good.buyers
     *
     * @mbggenerated
     */
    public Integer getBuyers() {
        return buyers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.buyers
     *
     * @param buyers the value for good.buyers
     *
     * @mbggenerated
     */
    public void setBuyers(Integer buyers) {
        this.buyers = buyers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.orders
     *
     * @return the value of good.orders
     *
     * @mbggenerated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.orders
     *
     * @param orders the value for good.orders
     *
     * @mbggenerated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.units_sold
     *
     * @return the value of good.units_sold
     *
     * @mbggenerated
     */
    public Integer getUnitsSold() {
        return unitsSold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.units_sold
     *
     * @param unitsSold the value for good.units_sold
     *
     * @mbggenerated
     */
    public void setUnitsSold(Integer unitsSold) {
        this.unitsSold = unitsSold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.revenue
     *
     * @return the value of good.revenue
     *
     * @mbggenerated
     */
    public Double getRevenue() {
        return revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.revenue
     *
     * @param revenue the value for good.revenue
     *
     * @mbggenerated
     */
    public void setRevenue(Double revenue) {
        this.revenue = revenue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.conversion_rate
     *
     * @return the value of good.conversion_rate
     *
     * @mbggenerated
     */
    public Double getConversionRate() {
        return conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.conversion_rate
     *
     * @param conversionRate the value for good.conversion_rate
     *
     * @mbggenerated
     */
    public void setConversionRate(Double conversionRate) {
        this.conversionRate = conversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.revenue_per_buyer
     *
     * @return the value of good.revenue_per_buyer
     *
     * @mbggenerated
     */
    public Double getRevenuePerBuyer() {
        return revenuePerBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.revenue_per_buyer
     *
     * @param revenuePerBuyer the value for good.revenue_per_buyer
     *
     * @mbggenerated
     */
    public void setRevenuePerBuyer(Double revenuePerBuyer) {
        this.revenuePerBuyer = revenuePerBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.wishlist_visitor
     *
     * @return the value of good.wishlist_visitor
     *
     * @mbggenerated
     */
    public Integer getWishlistVisitor() {
        return wishlistVisitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.wishlist_visitor
     *
     * @param wishlistVisitor the value for good.wishlist_visitor
     *
     * @mbggenerated
     */
    public void setWishlistVisitor(Integer wishlistVisitor) {
        this.wishlistVisitor = wishlistVisitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.wishlists
     *
     * @return the value of good.wishlists
     *
     * @mbggenerated
     */
    public Integer getWishlists() {
        return wishlists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.wishlists
     *
     * @param wishlists the value for good.wishlists
     *
     * @mbggenerated
     */
    public void setWishlists(Integer wishlists) {
        this.wishlists = wishlists;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.add_to_car_visitors
     *
     * @return the value of good.add_to_car_visitors
     *
     * @mbggenerated
     */
    public Integer getAddToCarVisitors() {
        return addToCarVisitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.add_to_car_visitors
     *
     * @param addToCarVisitors the value for good.add_to_car_visitors
     *
     * @mbggenerated
     */
    public void setAddToCarVisitors(Integer addToCarVisitors) {
        this.addToCarVisitors = addToCarVisitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.add_to_car_units
     *
     * @return the value of good.add_to_car_units
     *
     * @mbggenerated
     */
    public Integer getAddToCarUnits() {
        return addToCarUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.add_to_car_units
     *
     * @param addToCarUnits the value for good.add_to_car_units
     *
     * @mbggenerated
     */
    public void setAddToCarUnits(Integer addToCarUnits) {
        this.addToCarUnits = addToCarUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.store
     *
     * @return the value of good.store
     *
     * @mbggenerated
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.store
     *
     * @param store the value for good.store
     *
     * @mbggenerated
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.country
     *
     * @return the value of good.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.country
     *
     * @param country the value for good.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.datetime
     *
     * @return the value of good.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.datetime
     *
     * @param datetime the value for good.datetime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.create_time
     *
     * @return the value of good.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.create_time
     *
     * @param createTime the value for good.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}