package com.aso.itsdf07.entity;

import java.util.Date;

public class TransactionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Transaction_Date
     *
     * @mbggenerated
     */
    private Date transactionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Transaction_Type
     *
     * @mbggenerated
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Fee_Name
     *
     * @mbggenerated
     */
    private String feeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Transaction_Number
     *
     * @mbggenerated
     */
    private String transactionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Seller_SKU
     *
     * @mbggenerated
     */
    private String sellerSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Lazada_SKU
     *
     * @mbggenerated
     */
    private String lazadaSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.VAT_in_Amount
     *
     * @mbggenerated
     */
    private Double vatInAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.WHT_Amount
     *
     * @mbggenerated
     */
    private Double whtAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.WHT_included_in_Amount
     *
     * @mbggenerated
     */
    private String whtIncludedInAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Statement
     *
     * @mbggenerated
     */
    private String statement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Paid_Status
     *
     * @mbggenerated
     */
    private String paidStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Order_No
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Order_Item_No
     *
     * @mbggenerated
     */
    private String orderItemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Order_Item_Status
     *
     * @mbggenerated
     */
    private String orderItemStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Shipping_Provider
     *
     * @mbggenerated
     */
    private String shippingProvider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Shipping_Speed
     *
     * @mbggenerated
     */
    private String shippingSpeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Shipment_Type
     *
     * @mbggenerated
     */
    private String shipmentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Reference
     *
     * @mbggenerated
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.Comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.PaymentRefId
     *
     * @mbggenerated
     */
    private String paymentrefid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    private String country;
    private String store;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.id
     *
     * @return the value of transaction.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.id
     *
     * @param id the value for transaction.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Transaction_Date
     *
     * @return the value of transaction.Transaction_Date
     * @mbggenerated
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Transaction_Date
     *
     * @param transactionDate the value for transaction.Transaction_Date
     * @mbggenerated
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Transaction_Type
     *
     * @return the value of transaction.Transaction_Type
     * @mbggenerated
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Transaction_Type
     *
     * @param transactionType the value for transaction.Transaction_Type
     * @mbggenerated
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Fee_Name
     *
     * @return the value of transaction.Fee_Name
     * @mbggenerated
     */
    public String getFeeName() {
        return feeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Fee_Name
     *
     * @param feeName the value for transaction.Fee_Name
     * @mbggenerated
     */
    public void setFeeName(String feeName) {
        this.feeName = feeName == null ? null : feeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Transaction_Number
     *
     * @return the value of transaction.Transaction_Number
     * @mbggenerated
     */
    public String getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Transaction_Number
     *
     * @param transactionNumber the value for transaction.Transaction_Number
     * @mbggenerated
     */
    public void setTransactionNumber(String transactionNumber) {
        this.transactionNumber = transactionNumber == null ? null : transactionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Details
     *
     * @return the value of transaction.Details
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Details
     *
     * @param details the value for transaction.Details
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Seller_SKU
     *
     * @return the value of transaction.Seller_SKU
     * @mbggenerated
     */
    public String getSellerSku() {
        return sellerSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Seller_SKU
     *
     * @param sellerSku the value for transaction.Seller_SKU
     * @mbggenerated
     */
    public void setSellerSku(String sellerSku) {
        this.sellerSku = sellerSku == null ? null : sellerSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Lazada_SKU
     *
     * @return the value of transaction.Lazada_SKU
     * @mbggenerated
     */
    public String getLazadaSku() {
        return lazadaSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Lazada_SKU
     *
     * @param lazadaSku the value for transaction.Lazada_SKU
     * @mbggenerated
     */
    public void setLazadaSku(String lazadaSku) {
        this.lazadaSku = lazadaSku == null ? null : lazadaSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Amount
     *
     * @return the value of transaction.Amount
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Amount
     *
     * @param amount the value for transaction.Amount
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.VAT_in_Amount
     *
     * @return the value of transaction.VAT_in_Amount
     * @mbggenerated
     */
    public Double getVatInAmount() {
        return vatInAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.VAT_in_Amount
     *
     * @param vatInAmount the value for transaction.VAT_in_Amount
     * @mbggenerated
     */
    public void setVatInAmount(Double vatInAmount) {
        this.vatInAmount = vatInAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.WHT_Amount
     *
     * @return the value of transaction.WHT_Amount
     * @mbggenerated
     */
    public Double getWhtAmount() {
        return whtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.WHT_Amount
     *
     * @param whtAmount the value for transaction.WHT_Amount
     * @mbggenerated
     */
    public void setWhtAmount(Double whtAmount) {
        this.whtAmount = whtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.WHT_included_in_Amount
     *
     * @return the value of transaction.WHT_included_in_Amount
     * @mbggenerated
     */
    public String getWhtIncludedInAmount() {
        return whtIncludedInAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.WHT_included_in_Amount
     *
     * @param whtIncludedInAmount the value for transaction.WHT_included_in_Amount
     * @mbggenerated
     */
    public void setWhtIncludedInAmount(String whtIncludedInAmount) {
        this.whtIncludedInAmount = whtIncludedInAmount == null ? null : whtIncludedInAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Statement
     *
     * @return the value of transaction.Statement
     * @mbggenerated
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Statement
     *
     * @param statement the value for transaction.Statement
     * @mbggenerated
     */
    public void setStatement(String statement) {
        this.statement = statement == null ? null : statement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Paid_Status
     *
     * @return the value of transaction.Paid_Status
     * @mbggenerated
     */
    public String getPaidStatus() {
        return paidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Paid_Status
     *
     * @param paidStatus the value for transaction.Paid_Status
     * @mbggenerated
     */
    public void setPaidStatus(String paidStatus) {
        this.paidStatus = paidStatus == null ? null : paidStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Order_No
     *
     * @return the value of transaction.Order_No
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Order_No
     *
     * @param orderNo the value for transaction.Order_No
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Order_Item_No
     *
     * @return the value of transaction.Order_Item_No
     * @mbggenerated
     */
    public String getOrderItemNo() {
        return orderItemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Order_Item_No
     *
     * @param orderItemNo the value for transaction.Order_Item_No
     * @mbggenerated
     */
    public void setOrderItemNo(String orderItemNo) {
        this.orderItemNo = orderItemNo == null ? null : orderItemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Order_Item_Status
     *
     * @return the value of transaction.Order_Item_Status
     * @mbggenerated
     */
    public String getOrderItemStatus() {
        return orderItemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Order_Item_Status
     *
     * @param orderItemStatus the value for transaction.Order_Item_Status
     * @mbggenerated
     */
    public void setOrderItemStatus(String orderItemStatus) {
        this.orderItemStatus = orderItemStatus == null ? null : orderItemStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Shipping_Provider
     *
     * @return the value of transaction.Shipping_Provider
     * @mbggenerated
     */
    public String getShippingProvider() {
        return shippingProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Shipping_Provider
     *
     * @param shippingProvider the value for transaction.Shipping_Provider
     * @mbggenerated
     */
    public void setShippingProvider(String shippingProvider) {
        this.shippingProvider = shippingProvider == null ? null : shippingProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Shipping_Speed
     *
     * @return the value of transaction.Shipping_Speed
     * @mbggenerated
     */
    public String getShippingSpeed() {
        return shippingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Shipping_Speed
     *
     * @param shippingSpeed the value for transaction.Shipping_Speed
     * @mbggenerated
     */
    public void setShippingSpeed(String shippingSpeed) {
        this.shippingSpeed = shippingSpeed == null ? null : shippingSpeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Shipment_Type
     *
     * @return the value of transaction.Shipment_Type
     * @mbggenerated
     */
    public String getShipmentType() {
        return shipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Shipment_Type
     *
     * @param shipmentType the value for transaction.Shipment_Type
     * @mbggenerated
     */
    public void setShipmentType(String shipmentType) {
        this.shipmentType = shipmentType == null ? null : shipmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Reference
     *
     * @return the value of transaction.Reference
     * @mbggenerated
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Reference
     *
     * @param reference the value for transaction.Reference
     * @mbggenerated
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.Comment
     *
     * @return the value of transaction.Comment
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.Comment
     *
     * @param comment the value for transaction.Comment
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.PaymentRefId
     *
     * @return the value of transaction.PaymentRefId
     * @mbggenerated
     */
    public String getPaymentrefid() {
        return paymentrefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.PaymentRefId
     *
     * @param paymentrefid the value for transaction.PaymentRefId
     * @mbggenerated
     */
    public void setPaymentrefid(String paymentrefid) {
        this.paymentrefid = paymentrefid == null ? null : paymentrefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction.create_time
     *
     * @return the value of transaction.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction.create_time
     *
     * @param createTime the value for transaction.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getStore() {
        return store;
    }

    public void setStore(String store) {
        this.store = store;
    }
}