package com.aso.itsdf07.mapper;

import com.aso.itsdf07.entity.DemoEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface DemoEntityMapper {
    /**
     * 根据d_username进行查询
     *
     * @param dUsername
     * @return
     */
    DemoEntity getDemoEntity(@Param("username") String dUsername);

    /**
     * 查询t_demo表所有数据
     *
     * @return
     */
    List<DemoEntity> getAllDemoEntity();

    //-----------------------------------------------------------------------

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    int insert(DemoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    int insertSelective(DemoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    DemoEntity selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DemoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DemoEntity record);
}