package com.aso.itsdf07.mapper;

import com.aso.itsdf07.entity.GoodEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.List;

@Mapper
@Component
public interface GoodEntityMapper {

    /**
     * 匹配数据
     *
     * @param goodEntity
     * @return
     */
    int findGoodBySkuIdAndDataTime(GoodEntity goodEntity);

    /**
     * 更新数据
     *
     * @param goodEntity
     * @return
     */
    int updateGoodBySkuIdAndDataTime(GoodEntity goodEntity);

    /**
     * 条件查询
     *
     * @param goodEntity
     * @return
     */
    List<GoodEntity> findByParams(GoodEntity goodEntity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int insert(GoodEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int insertSelective(GoodEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    GoodEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodEntity record);
}